from __future__ import annotations

from blockcipher_nd.planning.four_role_attribution_gate import FourRoleProtocolSpec


PRESENT_CASE2_ATTRIBUTION_PROTOCOL = FourRoleProtocolSpec(
    claim_prefix="strict PRESENT r7",
    readiness_identity_label="R0",
    invalid_claim_scope="invalid strict-protocol architecture evidence",
    readiness_claim_scope="implementation readiness only; metrics not interpreted",
    research_claim_suffix="not formal, paper-scale, or breakthrough evidence",
    row_static_fields={
        "cipher": "PRESENT-80",
        "cipher_key": "present80",
        "structure": "SPN",
        "rounds": 7,
        "dataset_label_mode": "balanced_per_class",
        "input_difference": 9,
        "train_samples_total": None,
        "validation_samples_total": None,
        "final_test_samples_total": None,
        "final_test_repeats": 0,
        "pairs_per_sample": 16,
        "feature_encoding": "ciphertext_pair_bits",
        "negative_mode": "encrypted_random_plaintexts",
        "train_key": 0,
        "validation_key": int("11" * 10, 16),
        "key_rotation_interval": 0,
        "sample_structure": "zhang_wang_case2_official_mcnd",
        "difference_profile": "present_zhang_wang2022_mcnd",
        "difference_member": 0,
        "integral_active_nibble": 0,
        "integral_active_nibbles": [],
        "validation_integral_active_nibbles": [],
    },
    training_static_fields={
        "amsgrad": False,
        "dataset_label_mode": "balanced_per_class",
        "device": "cpu",
        "feature_encoding": "ciphertext_pair_bits",
        "key_schedule": "per_pair_random",
        "input_bits": 2048,
        "integral_active_nibble": 0,
        "integral_active_nibbles": [],
        "validation_integral_active_nibbles": [],
        "pair_bits": 128,
        "pairs_per_sample": 16,
        "key_rotation_interval": 0,
        "sample_structure": "zhang_wang_case2_official_mcnd",
        "selected_bit_indices": [],
        "train_dataset_storage": "disk",
        "validation_dataset_storage": "disk",
        "optimizer_state_transition": "reset_each_stage",
        "optimizer_state_reused": False,
        "optimizer_state_step_before": 0,
        "optimizer_session_call": 1,
        "train_eval_interval": 1,
        "loss": "mse",
        "optimizer": "adam",
        "learning_rate": 0.0001,
        "weight_decay": 0.00001,
        "lr_scheduler": "official_cyclic",
        "max_learning_rate": 0.002,
        "checkpoint_metric": "val_auc",
        "restore_best_checkpoint": True,
        "selected_checkpoint": "best",
        "early_stopping_patience": 8,
        "early_stopping_min_delta": 0.0001,
    },
    validation_static_fields={
        "cipher": "PRESENT-80",
        "structure": "SPN",
        "rounds": 7,
        "feature_encoding": "ciphertext_pair_bits",
        "negative_mode": "encrypted_random_plaintexts",
        "pairs_per_sample": 16,
        "dataset_label_mode": "balanced_per_class",
        "key_rotation_interval": 0,
        "sample_structure": "zhang_wang_case2_official_mcnd",
        "key_schedule": "per_pair_random",
        "integral_active_nibble": 0,
        "integral_active_nibbles": [],
    },
    cache_terminal_static_fields={
        "cipher_key": "present80",
        "rounds": 7,
        "dataset_label_mode": "balanced_per_class",
        "feature_encoding": "ciphertext_pair_bits",
        "negative_mode": "encrypted_random_plaintexts",
        "pairs_per_sample": 16,
        "key_rotation_interval": 0,
        "sample_structure": "zhang_wang_case2_official_mcnd",
        "difference_profile": "present_zhang_wang2022_mcnd",
        "difference_member": 0,
        "input_bits": 2048,
        "optimizer_state_transition": "reset_each_stage",
        "loss": "mse",
    },
    readiness_training_fields={
        "batch_size": 32,
        "dataset_cache_chunk_size": 64,
        "dataset_cache_workers": 1,
    },
    standard_training_fields={
        "batch_size": 256,
        "dataset_cache_chunk_size": 512,
        "dataset_cache_workers": 4,
    },
    readiness_seed_layout=(0,),
    readiness_samples_per_class=64,
    readiness_epochs=1,
    class_count=2,
)


__all__ = ["PRESENT_CASE2_ATTRIBUTION_PROTOCOL"]
